#!/usr/bin/env bash
# Cairn v2 one-command startup.
#
#   ./start.sh              compose stack (server + dispatcher), auto-prepared
#   ./start.sh --manual     server + dispatcher as host processes (dispatcher first)
#   ./start.sh stop         stop whichever mode is running
#   ./start.sh status       what is running, which socket, which config
#
# The script handles the two things that make Cairn v2 startup fiddly:
#   1. the Docker socket — rootless installs expose it under /run/user/<uid>,
#      rootful at /var/run/docker.sock; detection order: $DOCKER_HOST, the
#      docker CLI's active context, then the standard paths. Compose gets it
#      via CAIRN_DOCKER_SOCK in .env (mounted at /var/run/docker.sock inside).
#   2. dispatch.yaml + env vars — if no config exists, a verification-only
#      one is generated (no LLM keys needed); CAIRN_HOST_DATA is written to
#      .env so the sandbox's bind-mount sources resolve on the daemon side.
set -euo pipefail

cd "$(dirname "$0")"
ROOT="$(pwd)"

BOLD=$'\033[1m'; DIM=$'\033[2m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; RED=$'\033[31m'; OFF=$'\033[0m'
info() { printf '%s\n' "${GREEN}[*]${OFF} $*"; }
warn() { printf '%s\n' "${YELLOW}[!]${OFF} $*"; }
fail() { printf '%s\n' "${RED}[x]${OFF} $*" >&2; exit 1; }

have() { command -v "$1" >/dev/null 2>&1; }
have docker || fail "docker CLI not found — install docker first"

# ---------------------------------------------------------------- socket

detect_socket() {
  # 1) explicit environment wins
  if [ -n "${DOCKER_HOST:-}" ]; then
    echo "$DOCKER_HOST"; return
  fi
  # 2) the CLI's active context (what `docker` itself talks to)
  local ctx
  ctx=$(docker context inspect --format '{{ .Endpoints.docker.Host }}' 2>/dev/null || true)
  if [ -n "$ctx" ]; then echo "$ctx"; return; fi
  # 3) standard paths
  for candidate in "/var/run/docker.sock" "/run/user/$(id -u)/docker.sock"; do
    [ -S "$candidate" ] && { echo "unix://$candidate"; return; }
  done
  fail "no docker socket found — set DOCKER_HOST or check your docker install"
}

SOCKET_HOST=$(detect_socket)          # e.g. unix:///run/user/1000/docker.sock
SOCKET_PATH=${SOCKET_HOST#unix://}
[ -S "$SOCKET_PATH" ] || fail "docker socket $SOCKET_PATH does not exist"
docker info >/dev/null 2>&1 || fail "cannot talk to the daemon at $SOCKET_HOST (permission?)"

# ---------------------------------------------------------------- helpers

ensure_helper_images() {
  local img
  for img in python:3.13-slim docker:cli alpine/git; do
    docker image inspect "$img" >/dev/null 2>&1 || { info "pulling $img"; docker pull -q "$img" >/dev/null; }
  done
}

compose_config_present() { [ -f dispatch.yaml ]; }

# verification-only config: the deterministic pipeline needs no LLM keys.
# $1 = server url; $2 = mode ("compose" adds /cairn-datas paths + host_data_home)
gen_dispatch_config() {
  local server="$1" mode="$2"
  cat > dispatch.yaml <<EOF
# Generated by start.sh — verification-only (no LLM workers required).
# Edit freely: workers+keys for v1 hunt tasks, budget caps, sandbox limits.
server: "$server"
runtime:
  interval: 5
  max_workers: 4
  max_running_projects: 2
  max_project_workers: 2
  healthcheck_timeout: 20
  worker_healthcheck: "disabled"
  execution: "local"          # no worker containers; verification brings its own sandbox
  prompt_group: "default"
tasks:
  bootstrap: {timeout: 300, conclude_timeout: 90}
  reason: {timeout: 300, max_intents: 2}
  explore: {timeout: 300, conclude_timeout: 90}
workers: []
verification:
  enabled: true
  builder_image: "docker:cli"
  git_image: "alpine/git"
  probe_image: "python:3.13-slim"
  poc_image: "python:3.13-slim"
EOF
  if [ "$mode" = "compose" ]; then
    cat >> dispatch.yaml <<'EOF'
  # this file lives inside the dispatcher container; the shared volume is
  # mounted at /cairn-datas, and the daemon needs the HOST view for bind mounts
  evidence_home: "/cairn-datas/evidence"
  sandbox:
    data_home: "/cairn-datas/sandbox"
    host_data_home: "${CAIRN_HOST_DATA}/sandbox"
    image: "python:3.13-slim"
    collector_image: "python:3.13-slim"
EOF
  fi
}

write_env() {
  {
    echo "CAIRN_DOCKER_SOCK=$SOCKET_PATH"
    echo "CAIRN_HOST_DATA=$ROOT/datas/cairn"
  } > .env
}

wait_healthy() {
  local url="$1" tries="${2:-60}"
  for _ in $(seq 1 "$tries"); do
    curl -sf -o /dev/null "$url" && return 0
    sleep 2
  done
  return 1
}

sandbox_registered() {
  curl -s "http://localhost:8000/verification/system" 2>/dev/null | grep -q '"sandbox_available": *true'
}

# ---------------------------------------------------------------- commands

config_label() {
  [ -f dispatch.yaml ] || { echo "none yet (generated on start)"; return; }
  if grep -q '^workers: \[\]' dispatch.yaml; then
    echo "dispatch.yaml (verification-only)"
  elif grep -q '^workers:' dispatch.yaml; then
    echo "dispatch.yaml (with LLM workers)"
  else
    echo "dispatch.yaml"
  fi
}

cmd_status() {
  printf '%-16s %s\n' "socket:" "$SOCKET_HOST"
  printf '%-16s %s\n' "config:" "$(config_label)"
  if docker compose ps --status running -q 2>/dev/null | grep -q .; then
    docker compose ps
  else
    printf '%-16s %s\n' "compose:" "not running"
  fi
  if [ -f datas/run/cairn-server.pid ] && kill -0 "$(cat datas/run/cairn-server.pid)" 2>/dev/null; then
    printf '%-16s %s\n' "manual:" "server+dispatcher running (logs in datas/run/)"
  else
    printf '%-16s %s\n' "manual:" "not running"
  fi
  if curl -sf -o /dev/null http://localhost:8000/projects 2>/dev/null; then
    printf '%-16s %s\n' "api:" "up on :8000"
    sandbox_registered && printf '%-16s %s\n' "sandbox:" "registered with server" \
      || printf '%-16s %s\n' "sandbox:" "not registered yet (no dispatcher connected?)"
  else
    printf '%-16s %s\n' "api:" "down"
  fi
}

cmd_start_compose() {
  if ! compose_config_present; then
    gen_dispatch_config "http://cairn-server:8000" compose
    info "generated verification-only dispatch.yaml (workers: [] — add LLM workers later if you want v1 hunting)"
  fi
  write_env
  ensure_helper_images
  info "docker socket: $SOCKET_HOST → mounted into the dispatcher"
  info "building + starting the stack (first build takes a couple of minutes)…"
  docker compose up -d --build

  info "waiting for the server on :8000…"
  wait_healthy "http://localhost:8000/projects" 90 || fail "server did not become healthy — try: docker compose logs cairn-server"

  local waited=0
  until sandbox_registered || [ "$waited" -ge 45 ]; do sleep 2; waited=$((waited + 2)); done
  sandbox_registered && info "dispatcher connected, verification sandbox registered" \
    || warn "dispatcher has not registered the sandbox yet — check: docker compose logs cairn-dispatcher"

  echo
  echo "${BOLD}Cairn v2 is up${OFF}"
  echo "  console      ${GREEN}http://localhost:8000/verify${OFF}"
  echo "  v1 console   http://localhost:8000/"
  echo "  api          http://localhost:8000/docs"
  echo "  ingest       curl -X POST localhost:8000/claims -H 'content-type: application/json' -d @claim.json"
  echo "  full-auto    uv run --project cairn cairn auto --claim claim.json"
  echo "  stop         ./start.sh stop"
}

cmd_start_manual() {
  if ! compose_config_present; then
    gen_dispatch_config "http://127.0.0.1:8000" manual
    info "generated verification-only dispatch.yaml (host paths — dispatcher and daemon see the same files)"
  fi
  ensure_helper_images
  export DOCKER_HOST="$SOCKET_HOST"
  info "docker socket: $SOCKET_HOST (exported for the sandbox SDK)"
  mkdir -p datas/run

  info "starting dispatcher first (it retries until the server is up)…"
  uv run --project cairn cairn dispatch --config dispatch.yaml > datas/run/dispatcher.log 2>&1 &
  local dispatcher_pid=$!
  uv run --project cairn cairn serve --host 0.0.0.0 > datas/run/server.log 2>&1 &
  local server_pid=$!
  echo "$dispatcher_pid $server_pid" > datas/run/pids
  echo "$server_pid" > datas/run/cairn-server.pid
  trap 'kill "$dispatcher_pid" "$server_pid" 2>/dev/null; rm -f datas/run/pids datas/run/cairn-server.pid' EXIT

  info "waiting for the server on :8000…"
  wait_healthy "http://localhost:8000/projects" 45 || fail "server did not come up — see datas/run/server.log"
  info "server up; dispatcher will register the sandbox within one interval"

  echo
  echo "${BOLD}Cairn v2 is up (manual mode)${OFF}"
  echo "  console      ${GREEN}http://localhost:8000/verify${OFF}"
  echo "  logs         datas/run/{server,dispatcher}.log   (tail -f)"
  echo "  stop         ${BOLD}Ctrl-C${OFF} (both processes stop with the script)"
  wait
}

cmd_stop() {
  if docker compose ps -q 2>/dev/null | grep -q .; then
    info "stopping the compose stack"
    docker compose down
  fi
  if [ -f datas/run/pids ]; then
    info "stopping manual processes"
    kill $(cat datas/run/pids) 2>/dev/null || true
    rm -f datas/run/pids datas/run/cairn-server.pid
  fi
  info "stopped"
}

case "${1:-start}" in
  start)    cmd_start_compose ;;
  --manual) cmd_start_manual ;;
  stop)     cmd_stop ;;
  status)   cmd_status ;;
  --help|-h)
    sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'
    ;;
  *) fail "unknown command: $1 (try ./start.sh --help)" ;;
esac
